### PR TITLE
rename config/version to config/flexiblesusy-version

### LINKED ISSUE #267: header conflict after boost update
There's a problem I'm seeing after upgrade from boost 1.71 to 1.74.
```
Building src/string_format.o
In file included from src/slha_io.cpp:27:
In file included from slhaea/slhaea.h:25:
In file included from /usr/include/boost/algorithm/string/classification.hpp:16:
In file included from /usr/include/boost/range/value_type.hpp:18:
In file included from /usr/include/boost/range/config.hpp:14:
In file included from /usr/include/boost/detail/workaround.hpp:8:
In file included from /usr/include/boost/config/workaround.hpp:41:
In file included from /usr/include/boost/config.hpp:44:
In file included from /usr/include/boost/config/detail/select_stdlib_config.hpp:24:
config/version:1:1: error: expected unqualified-id
2.5.0
^
In file included from src/string_format.cpp:20:
In file included from /usr/include/boost/lexical_cast.hpp:21:
In file included from /usr/include/boost/config.hpp:44:
In file included from /usr/include/boost/config/detail/select_stdlib_config.hpp:24:
config/version:1:1: error: expected unqualified-id
2.5.0
^
```
Seems boost thinks `version` is its file.
Do we need the file `config/version`, and if yes which parts of the code are using it so that maybe we could rename it.

### PR DESCRIPTION
**Pull request by Expander**
to fix a compilation error with boost 1.74

fixes #267

### CODE REVIEW

**Comment by Expander** [comment]
@wkotlarski Would you mind testing this PR?

**Review by wkotlarski — APPROVED** [review]

**Comment by Expander** [comment]
Thanks!

**Comment by wkotlarski** [comment]
Can we delete this branch?
