### ISSUE TITLE
*_vertices_1.cpp fails to compile

### ISSUE THREAD

**Issue by Expander** [FlexibleSUSY/FlexibleSUSY#344]
see https://flexiblesusy.hepforge.org/test/FlexibleSUSY/build-all.log

The error is:
~~~
g++ [...] models/rootMSSM/cxx_qft/rootMSSM_vertices_1.o

models/rootMSSM/cxx_qft/rootMSSM_vertices_1.cpp:45:19: error: stray ‘`’ in program
    const int SARAH`gt3 = indices[0];
                   ^
models/rootMSSM/cxx_qft/rootMSSM_vertices_1.cpp:46:19: error: stray ‘`’ in program
    const int SARAH`gt1 = indices[1];
                   ^
...
~~~
System information:
* SARAH 4.14.3
* Mathematica 10.2
* g++ 7.5.0

**Comment by Expander** [comment]
I cannot reproduce the issue on my personal machine:
* SARAH 4.14.3
* Wolfram Language 12.0.0 Engine for Linux x86
* clang++ 10.0.1

**Comment by wkotlarski** [comment]
This looks like a fail of this block of code
```mathematica
   If[FlexibleSUSY`FSEnableParallelism,
      (* without this CForm includes context in name of symbols
         such that we get for example SARAH_g1 instead of g1 in
         generated C++ code *)
      ParallelEvaluate[
         (BeginPackage[#];EndPackage[];
          (* prevent shdw warning with Susyno`LieGroups`M: *)
          Off[Remove::remal];       
          Remove[Susyno`LieGroups`M];
          On[Remove::remal];
         )& /@ contextsToDistribute,
         DistributedContexts->Automatic         
      ];
```
I also cannot reproduce it.

**Comment by Expander** [comment]
Could it be, that this is an issue with Mathematica 10.2?
I could try to run the nightly tests with Mathematica 12 (and maybe also 11).

**Comment by wkotlarski** [comment]
Maybe, hard to say. I'm using 11.2.

**Comment by Expander** [comment]
There is 11.3.0 on the RWTH cluster. I'll use that for the next nightly run.

**Comment by Expander** [comment]
The build with 11.3.0 fails for strange reasons.
Last night the issue was that the model-specific dependencies for the `MSSMMuBMu` were not detected correctly:
~~~
Updating model-specific modules in models/MSSMMuBMu/module.mk ... (SM)                                                                                                                                   
~~~
On my machine it says:
~~~
Updating model-specific modules in models/MSSMMuBMu/module.mk ... (SM MSSM_higgs)                                                                                                                                 
~~~
The night before, it failed because Mathematica crashed. The same issue may be the reason for last night's failure.

**Comment by Expander** [comment]
There is also a Mathematica crash that leads to some files don't get generated:
~~~
g++: error: models/NUHMSSM/NUHMSSM_librarylink.cpp: No such file or directory
~~~

**Comment by wkotlarski** [comment]
I remember I didn't upgrade to 11.3 because I had some problems with FS.

**Comment by Expander** [comment]
Oh. :)

**Comment by Expander** [comment]
I'll try to reduce the number of cores, maybe this helps ...

**Comment by Expander** [comment]
With one core less it is a bit better now.
It still fails due to a linking error with collier, but that's a problem with the conan package.

Anyway, I think there is no real issue, besides the fact that Mathematica crashes and the conan package for collier contains a bug.

**Comment by wkotlarski** [comment]
I wouldn't mind. v11 is 5 years old. Not really a cutting edge release.

**Comment by Expander** [comment]
You are right, let's increase the required Mathematica version to 11 then.
