### ISSUE TITLE
bug in recent commit

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#211]
There seems to be a bug introduced in 30b85a74b132cf30b1f5dc4ad8ff6cca3bb4f292
```
clang++ -Iconfig -Isrc -Ifflite -Islhaea -Idoc -Imeta -Itemplates -Imodels/SM -Imodels/THDMII -Imodels/MSSM -Imodels/CMSSM -Imodels/CMSSMCKM -Imodels/MRSSM2 -Imodels/MRSSM2CKM -Imodels/MSSMCPV -Imodels/MSSMNoFV -Imodels/ScalarLeptoquarks -Imodels/LRLR -Itest -I. -Itest/SOFTSUSY -Imodel_specific/SM -Imodel_specific/SM_thresholds -Imodel_specific/SplitMSSM -Imodel_specific/MSSM_higgs -Imodel_specific/MSSM_thresholds -Imodel_specific/NMSSM_higgs -I/usr/include -I/usr/include/eigen3 -I/usr/include  -std=c++14 -O2 -fPIC -c test/test_MRSSM2_l_to_lgamma.cpp -o test/test_MRSSM2_l_to_lgamma.o
test/test_MRSSM2_l_to_lgamma.cpp:68:19: error: variable has incomplete type 'flexiblesusy::Physical_input'
   Physical_input physical_inputs;
                  ^
models/MRSSM2/MRSSM2_utilities.hpp:41:7: note: forward declaration of 'flexiblesusy::Physical_input'
class Physical_input;
      ^
1 error generated.
make: *** [Makefile:249: test/test_MRSSM2_l_to_lgamma.o] Error 1
```
